jetty:
  context: /
  connectors:
    - port: 8080
    - port: 8443
jdbc:
  appds:
    url: "jdbc:h2:file:./src/main/resources/db/beerdb2.h2"
    username:
    password:
    driverClassName: org.h2.Driver
    jmxEnabled: true
    jmxObjectName: appds
    initialSize: 2