jetty:
  context: /
  connectors:
    - port: 8080
    - port: 8443
jdbc:
  appds:
    url: "jdbc:h2:file:./src/main/resources/db/beerdb2.h2"
    username:
    password:
    driverClassName: org.h2.Driver
    jmxEnabled: true
    jmxObjectName: appds
    initialSize: 2
log:
  level: debug
  appenders:
    - type: file
      logFormat: '%c{20}: %m%n'
      file: 'target/logs/rotate-by-size-and-history-and-totalsize/logfile-current.log'
      rollingPolicy:
        type: sizeAndTime
        fileNamePattern: 'target/logs/rotate-by-size-and-history-and-totalsize/logfile-%d{yyyyMMDDHHmmss}.%i.log'
        historySize: 5
        fileSize: 50
        totalSize: 150