jetty:
  context: /
  connectors:
    - port: 8080
    - port: 8443
jdbc:
  appds:
    url: "jdbc:h2:file:./db/beer.h2"
    driverClassName: org.h2.Driver
    jmxEnabled: true
    jmxObjectName: appds
    initialSize: 2