package ar.com.phosgenos

import application.controllers.impl.CategoryController
import com.google.inject.Binder
import com.google.inject.Module
import com.google.inject.multibindings.Multibinder;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luis' at '21/01/17 20:51' with Gradle 3.1
 *
 * @author luis, @date 21/01/17 20:51
 */
import io.bootique.Bootique
import io.bootique.jersey.JerseyModule

class Application {
    static void main(String[] args) {

        Module jerseyModule = buildJerseyModule()

        Bootique.app(args)
                .module(jerseyModule)
                .autoLoadModules()
                .run()
    }

    private static Module buildJerseyModule() {
        [configure: { Binder binder ->

            Multibinder<Object> multibinder = JerseyModule.contributeResources(binder)

            [HelloResource, CategoryController].each {
                multibinder.addBinding().to(it)
            }

        }] as Module
    }

    boolean someLibraryMethod() {
        return false
    }
}
