package ar.com.phosgenos

import com.google.inject.Binder
import com.google.inject.Module;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luis' at '21/01/17 20:51' with Gradle 3.1
 *
 * @author luis, @date 21/01/17 20:51
 */
import io.bootique.Bootique
import io.bootique.jersey.JerseyModule

class Application {
    static void main(String[] args) {

        Module module = [configure: { Binder binder ->
            JerseyModule.contributeResources(binder)
                    .addBinding()
                    .to(HelloResource)
        }] as Module

        Bootique.app(args)
                .module(module)
                .autoLoadModules()
                .run()
    }

    boolean someLibraryMethod() {
        return false
    }
}
